---
- name: Getty path
  ansible.builtin.file:
    path: "/etc/systemd/system/getty@tty1.service.d"
    state: directory
  when:
    - ansible_facts['distribution'] == 'Archlinux'

- name: Autologin user
  ansible.builtin.template:
    src: getty_override.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
  when:
    - ansible_facts['distribution'] == 'Archlinux'
