---
- name: Create boot loader entry path
  ansible.builtin.file:
    path: "/boot/loader/entries"
    state: directory
  when: ansible_facts['distribution'] == 'Archlinux'

- name: kernel boot loader config
  ansible.builtin.template:
    src: arch_linux.j2
    dest: /boot/loader/entries/arch_linux.conf
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: boot loader config
  ansible.builtin.template:
    src: loader.j2
    dest: /boot/loader/loader.conf
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Set systemd boot install path
  ansible.builtin.shell:
    cmd: |
      bootctl --path=/boot install
  when: ansible_facts['distribution'] == 'Archlinux'
