---
- name: Create filesystems for LVM
  community.general.filesystem:
    fstype: "{{ filesystem.type }}"
    dev: "/dev/{{ lvm_name }}/{{ filesystem.name }}"
  loop: "{{ file_systems }}"
  loop_control:
    loop_var: filesystem
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Create boot filesystem
  ansible.builtin.shell:
    cmd: |
      mkfs.fat -F32 "{{ disk }}p1"
  when: ansible_facts['distribution'] == 'Archlinux'
