---
- name: Allow ssh
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    source: "{{ management_network }}"
    limit: 6/minute
    jump: ACCEPT
  become: "yes"
  when: ansible_facts['distribution'] == 'Debian'

- name: Allow ssh ansible
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    source: "{{ ip_ansible }}"
    jump: ACCEPT
  become: "yes"
  when:
    - ansible_facts['distribution'] == 'Debian'
    - ip_ansible is defined

- name: Allow ssh backup
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    source: "{{ backup_host }}"
    jump: ACCEPT
  become: "yes"
  when:
    - ansible_facts['distribution'] == 'Debian'
    - backup_host is defined

- name: Allow icmp
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    source: "{{ management_network }}"
    jump: ACCEPT
  become: "yes"
  when: ansible_facts['distribution'] == 'Debian'

- name: Allow loopback
  ansible.builtin.iptables:
    chain: INPUT
    source: "127.0.0.1"
    in_interface: lo
    jump: ACCEPT
  become: "yes"
  when: ansible_facts['distribution'] == 'Debian'

- name: Allow established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: "yes"
  when: ansible_facts['distribution'] == 'Debian'

- name: Drop inbound by default
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
  when: ansible_facts['distribution'] == 'Debian'

- name: Allow outbound by default
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT
  when: ansible_facts['distribution'] == 'Debian'

- name: Drop forwarding by default
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP
  when: ansible_facts['distribution'] == 'Debian'

- name: Drop inbound by default ipv6
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
    ip_version: ipv6
  when: ansible_facts['distribution'] == 'Debian'

- name: Allow outbound by default ipv6
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT
    ip_version: ipv6
  when: ansible_facts['distribution'] == 'Debian'

- name: Drop forwarding by default ipv6
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP
    ip_version: ipv6
  when: ansible_facts['distribution'] == 'Debian'

- name: Save Iptables Rules
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4
  when: ansible_facts['distribution'] == 'Debian'

- name: Save Iptables Rules ipv6
  community.general.iptables_state:
    ip_version: ipv6
    table: filter
    state: saved
    path: /etc/iptables/rules.v6
  when: ansible_facts['distribution'] == 'Debian'
