# Place hosts in here and roles to run
---
- hosts: backup
  roles:
    - standard_ssh
    - standard_qemu_guest_agent
    - standard_update_packages
    - standard_patching
    - standard_cron
    - standard_iptables
    - backup
