---
- hosts: desktop
  roles:
    - locale_config
    - multilib_config
    - install_packages_univ
    - enable_firewalld
    - enable_apparmor
    - default_firewalld_config
    - configure_aliases
    - configure_timezone
    - user_profile_path
    - configure_git
    - configure_psd
    - aur_builds
    - enable_bluetooth
    - enable_paccache
    - pacman_hooks_directory
    - fwupd_config
    - reflector_config
    - enable_cups
    - configure_sudo
    - configure_virt_manager
    - configure_terminal
    - user_autologin
    - configure_firejail
    - configure_scripts
    - configure_home_folder
