- hosts: localhost

- name: Run ansible config playbook
  import_playbook: ansible.yml

- name: Run backup config playbook
  import_playbook: backup.yml

- name: Run navidrome config playbook
  import_playbook: navidrome.yml

- name: Run nextcloud config playbook
  import_playbook: nextcloud.yml

- name: Run vaultwarden config playbook
  import_playbook: vaultwarden.yml

#- name: Run all_services config playbook
#  import_playbook: all_services.yml
