---
- hosts: laptop
  vars:
    ansible_ssh_user: root
  roles:
    - configure_locales
    - setup_efi_partition
    - setup_lvm_encrypted_partition
    - setup_lvm
    - setup_filesystems
    - initial_install_mount_filesystems
    - initial_Arch_install
