---
- name: Configure vm1
  hosts: vm1
  vars:
    nextcloud_uid: "33"
    nextcloud_gid: "33"
    apply_runtime_changes_on_reboot: true
  module_defaults:
    ansible.posix.firewalld:
      offline: "{{ apply_runtime_changes_on_reboot | bool }}"
  roles:
    - standard_ssh
    - standard_qemu_guest_agent
    - standard_update_packages
    - configure_timezone
    - standard_cron
    - dynamic_dns
    - standard_firewalld
    - standard_podman
    - standard_rclone
    - standard_selinux
    - backup
    - ansible
    - reverse_proxy
    - nextcloud
    - paperless_ngx
    - navidrome
    - vaultwarden
    - semaphore
    - standard_cleanup
