---
- name: Configure vm2
  hosts: vm2
  vars:
    apply_runtime_changes_on_reboot: true
    standard_update_enable_epel: true
    standard_selinux_extra_booleans: "{{ vm2_selinux_extra_booleans | default([{'name': 'domain_can_mmap_files', 'state': true}]) }}"
  module_defaults:
    ansible.posix.firewalld:
      offline: "{{ apply_runtime_changes_on_reboot | bool }}"
  roles:
    - standard_ssh
    - standard_qemu_guest_agent
    - standard_update_packages
    - configure_timezone
    - standard_cron
    - standard_firewalld
    - dev_vm
    - standard_selinux
    - standard_cleanup
