---
- name: Configure kernel
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: "^#?HOOKS="
    line: HOOKS=(base udev autodetect keyboard keymap consolefont modconf block encrypt lvm2 filesystems fsck)
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Run kernel build
  ansible.builtin.shell:
    cmd: |
      mkinitcpio -P
  when: ansible_facts['distribution'] == 'Archlinux'
