---
- name: Reboot machine
  ansible.builtin.reboot:
    reboot_timeout: 600
  when:
    - inventory_hostname != 'ansible'

- name: Reboot machine
  ansible.builtin.command: shutdown -r +1
  async: 40
  poll: 0
  when:
    - inventory_hostname == 'ansible'
