---
- name: Create user profile path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/.profile"
    state: touch
    owner: "{{ user_name }}"
  when:
    - ansible_facts['distribution'] == 'Archlinux'
