---
- name: Get Luks or LVM partition uuid
  ansible.builtin.shell:
    cmd: |
      blkid -o value -s UUID "{{ disk }}p2"
  register: luks_uuid
  when:
    - ansible_facts['distribution'] == 'Archlinux'

- name: Get file system uuids
  ansible.builtin.shell:
    cmd: |
      blkid -o value -s UUID "/dev/{{ lvm_name }}/{{ filesystem.name }}"
  loop: "{{ file_systems }}"
  loop_control:
    loop_var: filesystem
  register: filesystem_uuids
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Save file system uuids
  ansible.builtin.include_tasks: save_uuids.yml
  loop: "{{ file_systems }}"
  loop_control:
    loop_var: filesystem

- name: Get boot partition uuid
  ansible.builtin.shell:
    cmd: |
      blkid -o value -s UUID "{{ disk }}p1"
  register: boot_uuid
  when: ansible_facts['distribution'] == 'Archlinux'
