---
- name: Set user home ownership to user
  ansible.builtin.shell:
    cmd: |
      chown -R {{ user_name }}:{{ user_name }} /home/{{ user_name }}
  when:
    - ansible_facts['distribution'] == 'Archlinux'
