---
- name: Create apcontroller container network
  ansible.builtin.shell:
    cmd: |
      podman network create ap_container_net
  ignore_errors: true
  when: ansible_facts['distribution'] == 'Debian' ansible_facts['distribution'] == 'Archlinux'

- name: Create APController container path
  ansible.builtin.file:
    path: "{{ apcontroller_path }}"
    state: directory
    mode: 0770
    owner: 508
    group: 508
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create APController data path
  ansible.builtin.file:
    path: "{{ apcontroller_path }}/data"
    state: directory
    mode: 0770
    owner: 508
    group: 508
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create APController work path
  ansible.builtin.file:
    path: "{{ apcontroller_path }}/work"
    state: directory
    mode: 0770
    owner: 508
    group: 508
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create APController logs path
  ansible.builtin.file:
    path: "{{ apcontroller_path }}/logs"
    state: directory
    mode: 0770
    owner: 508
    group: 508
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: APcontroller Service
  ansible.builtin.template:
    src: apcontroller.service.j2
    dest: "/etc/systemd/system/apcontroller.service"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Enable APcontroller
  ansible.builtin.systemd:
    name: apcontroller.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Apcontroller script
  ansible.builtin.template:
    src: apcontroller.sh.j2
    dest: "/usr/local/bin/apcontroller.sh"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Update apcontroller container script
  ansible.builtin.template:
    src: update_apcontroller_container.sh.j2
    dest: "/usr/local/bin/update_apcontroller_container.sh"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'
