# Credits
# https://www.decodingdevops.com/ansible-when-file-exists/
# https://techviewleo.com/list-of-ansible-os-family-distributions-facts/

---
- name: Install packages OpenWrt
  community.general.opkg:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'OpenWrt'

- name: Set default action for public to drop
  ansible.posix.firewalld:
    zone: public
    target: DROP
    permanent: yes
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create new zone and set it to drop
  ansible.posix.firewalld:
    zone: homelab
    target: DROP
    permanent: yes
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Set ipv4 source for zone
  ansible.posix.firewalld:
    zone: homelab
    source: "{{ network_prefix }}"
    permanent: yes
    state: enabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Set ipv6 source for zone
  ansible.posix.firewalld:
    zone: homelab
    source: "fe80::/10"
    permanent: yes
    state: enabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Enable icmp block inversion
  ansible.posix.firewalld:
    zone: homelab
    icmp_block_inversion: yes
    permanent: yes
    state: enabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Allow SSH
  ansible.posix.firewalld:
    zone: homelab
    service: ssh
    permanent: yes
    state: enabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Allow icmp
  ansible.posix.firewalld:
    zone: homelab
    icmp_block: echo-request
    permanent: yes
    state: enabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Disable SSH in default zone
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: disabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Disable dhcpv6-client in default zone
  ansible.posix.firewalld:
    zone: public
    service: dhcpv6-client
    permanent: yes
    state: disabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: Disable mdns in default zone
  ansible.posix.firewalld:
    zone: public
    service: mdns
    permanent: yes
    state: disabled
  when: ansible_facts['os_family'] == 'RedHat'

- name: SSH configuration
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/1-sshd_custom
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['os_family'] == 'RedHat'
