---
- name: Enable virt manager
  ansible.builtin.systemd:
    name: libvirtd.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Archlinux'

- name: set libvirt socket group
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: ^#?unix_sock_group =
    line: unix_sock_group = "libvirt"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: set libvirt socket permissions
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: ^#?unix_sock_rw_perms =
    line: unix_sock_rw_perms = "0770"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Add libviirt group
  ansible.builtin.group:
    name: libvirt
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: libvirt
    append: yes
  when: ansible_facts['distribution'] == 'Archlinux'
