---
# https://docs.linuxserver.io/general/swag

- name: Create nextcloud and postgres container network
  ansible.builtin.shell:
    cmd: |
      podman network create --subnet 172.16.1.8/29 nextcloud_container_net
  ignore_errors: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create postgres database container path
  ansible.builtin.file:
    path: "{{ postgres_path }}"
    state: directory
    owner: root
    group: root
    mode: "0777"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create postgres database custom-init path
  ansible.builtin.file:
    path: "{{ postgres_path }}/custom-init"
    state: directory
    owner: root
    group: root
    mode: "0777"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create Nextcloud container path
  ansible.builtin.file:
    path: "{{ nextcloud_path }}"
    state: directory
    owner: "33"
    group: "33"
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Mount Disk for backups
  ansible.posix.mount:
    path: "{{ nextcloud_path }}"
    src: "{{ nextcloud_disk }}"
    fstype: ext4
    opts: rw,auto
    state: mounted
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create Nextcloud base container path
  ansible.builtin.file:
    path: "{{ nextcloud_path }}/base"
    state: directory
    owner: "33"
    group: "33"
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create Nextcloud data container path
  ansible.builtin.file:
    path: "{{ nextcloud_path }}/data"
    state: directory
    owner: "33"
    group: "33"
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create Nextcloud config container path
  ansible.builtin.file:
    path: "{{ nextcloud_path }}/config"
    state: directory
    owner: "33"
    group: "33"
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create Nextcloud apps container path
  ansible.builtin.file:
    path: "{{ nextcloud_path }}/apps"
    state: directory
    owner: "33"
    group: "33"
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Redis Service
  ansible.builtin.template:
    src: redis_container.service.j2
    dest: "/etc/systemd/system/redis_container.service"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Enable Redis
  ansible.builtin.systemd:
    name: redis_container.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: postgres Service
  ansible.builtin.template:
    src: postgres_container.service.j2
    dest: "/etc/systemd/system/postgres_container.service"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Enable postgres
  ansible.builtin.systemd:
    name: postgres_container.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Nextcloud Service
  ansible.builtin.template:
    src: nextcloud_container.service.j2
    dest: "/etc/systemd/system/nextcloud_container.service"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Enable Nextcloud
  ansible.builtin.systemd:
    name: nextcloud_container.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Redis script
  ansible.builtin.template:
    src: redis_container.sh.j2
    dest: "/usr/local/bin/redis_container.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Nextcloud script
  ansible.builtin.template:
    src: nextcloud_container.sh.j2
    dest: "/usr/local/bin/nextcloud_container.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Postgres script
  ansible.builtin.template:
    src: postgres_container.sh.j2
    dest: "/usr/local/bin/postgres_container.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Postgres db_wrapper script
  ansible.builtin.template:
    src: db_wrapper.sh.j2
    dest: "{{ postgres_path }}/custom-init/db_wrapper.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Backup databases and paperless script
  ansible.builtin.template:
    src: backup_db_paperless.sh.j2
    dest: "/usr/local/bin/backup_db_paperless.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'
