---
- name: Mount storage for Nextcloud
  ansible.posix.mount:
    path: "/home/{{ user_name }}/nextcloud/data"
    src: "{{ nextcloud_storage }}"
    boot: yes
    opts: rw,nofail
    state: mounted
    fstype: ext4
  when: ansible_distribution == 'Rocky'

- name: Create postgres database container path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/postgres"
    state: directory
  when: ansible_distribution == 'Rocky'

- name: Create Nextcloud base container path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/nextcloud/base"
    state: directory
  when: ansible_distribution == 'Rocky'

- name: Create Nextcloud data container path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/nextcloud/data"
    state: directory
  when: ansible_distribution == 'Rocky'

- name: Create Nextcloud config container path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/nextcloud/config"
    state: directory
  when: ansible_distribution == 'Rocky'

- name: Create Nextcloud apps container path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/nextcloud/apps"
    state: directory
  when: ansible_distribution == 'Rocky'

- name: Nextcloud Service
  ansible.builtin.template:
    src: nextcloud_container.service.j2
    dest: "/etc/systemd/system/nextcloud_container.service"
  when: ansible_distribution == 'Rocky'

- name: Enable Nextcloud
  ansible.builtin.systemd:
    name: nextcloud_container.service
    enabled: yes
  when: ansible_distribution == 'Rocky'

- name: Nextcloud Pod file
  ansible.builtin.template:
    src: nextcloud.yml.j2
    dest: "/home/{{ user_name }}/kubernetes/nextcloud.yml"
  when: ansible_distribution == 'Rocky'
