---
- name: Install nextcloud packages
  apt:
    name: "{{ nextcloud_packages }}"
    state: latest
    update_cache: "yes"
  when: ansible_facts['os_family'] == 'Debian'

- name: Download nextcloud
  get_url:
    url: https://download.nextcloud.com/server/releases/{{ nextcloud_file }}
    dest: /tmp
    checksum: sha256:{{ nextcloud_checksum }}

- name: Create www folder
  ansible.builtin.file:
    path: "/var/www/"
    state: directory

- name: Extract nextcloud zip folder
  ansible.builtin.unarchive:
    src: /tmp/{{ nextcloud_file }}
    dest: /var/www

- name: Apache nextcloud config
  ansible.builtin.template:
    src: apache_nextcloud.j2
    dest: /etc/apache2/sites-available/nextcloud.conf

- name: Enable Apache nextcloud config
  ansible.builtin.shell:
    cmd: |
      a2ensite nextcloud.conf
      a2enmod rewrite
      a2enmod headers
      a2enmod env
      a2enmod dir
      a2enmod mime
      a2enmod ssl
      a2ensite default-ssl
      service apache2 restart

- name: Install nextcloud
  ansible.builtin.shell:
    cmd: |
      cd /var/www/nextcloud/
      php occ  maintenance:install --database "mysql" --database-name "nextcloud"  --database-user "root" --database-pass "{{ nextcloud_db_root_password }}" --admin-user "admin" --admin-pass "{{ nextcloud_db_admin_password }}"

- name: Set nextcloud folder owner
  ansible.builtin.file:
    path: "/var/www/nextcloud/"
    state: directory
    recurse: yes
    owner: "www-data"
    group: "www-data"

- name: Allow http
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    source: "{{ network_prefix }}"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
  become: "yes"

- name: Allow http ipv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    source: "fe80::/10"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"

- name: Allow https
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    source: "{{ network_prefix }}"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
  become: "yes"

- name: Allow https ipv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    source: "fe80::/10"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"

- name: Save Iptables Rules
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4

- name: Save Iptables Rules ipv6
  community.general.iptables_state:
    ip_version: ipv6
    table: filter
    state: saved
    path: /etc/iptables/rules.v6
