---
- name: Install nextcloud
  ansible.builtin.shell:
    cmd: |
      snap install nextcloud
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Copy ssl cert
  ansible.builtin.copy:
    src: "/etc/letsencrypt/live/{{ ssl_cert }}/"
    dest: /var/snap/nextcloud/current/certs/custom/
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Install ssl cert
  ansible.builtin.shell:
    cmd: |
      nextcloud.enable-https custom -s cert.pem privkey.pem chain.pem
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Set custom domains
  ansible.builtin.shell:
    cmd: |
      snap run nextcloud.occ config:system:set trusted_domains 1 --value={{ domain_name }}
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Allow http
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    source: "{{ network_prefix }}"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
  become: "yes"
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Allow http ipv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    source: "fe80::/10"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Allow https
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    source: "{{ network_prefix }}"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
  become: "yes"
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Allow https ipv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    source: "fe80::/10"
    in_interface: "{{ interface_name }}"
    jump: ACCEPT
    ip_version: ipv6
  become: "yes"
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Save Iptables Rules
  community.general.iptables_state:
    ip_version: ipv4
    table: filter
    state: saved
    path: /etc/iptables/rules.v4
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Save Iptables Rules ipv6
  community.general.iptables_state:
    ip_version: ipv6
    table: filter
    state: saved
    path: /etc/iptables/rules.v6
  when:
    - ansible_facts['os_family'] == 'Debian'
