---
- name: Inspect semaphore container network
  ansible.builtin.command:
    argv:
      - podman
      - network
      - inspect
      - semaphore_container_net
  register: semaphore_network
  changed_when: false
  failed_when: false

- name: Create semaphore container network
  ansible.builtin.command:
    argv:
      - podman
      - network
      - create
      - semaphore_container_net
  when: semaphore_network.rc != 0

- name: Create semaphore secret directory
  ansible.builtin.file:
    path: "{{ secret_env_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Create semaphore config directory
  ansible.builtin.file:
    path: /etc/semaphore
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Semaphore env file
  ansible.builtin.template:
    src: semaphore.env.j2
    dest: "{{ secret_env_dir }}/semaphore.env"
    owner: root
    group: root
    mode: "0600"

- name: Semaphore known hosts file
  ansible.builtin.template:
    src: ssh_known_hosts.j2
    dest: /etc/semaphore/ssh_known_hosts
    owner: root
    group: root
    mode: "0600"

- name: Semaphore service
  ansible.builtin.template:
    src: semaphore.service.j2
    dest: /etc/systemd/system/semaphore.service

- name: Enable semaphore
  ansible.builtin.systemd:
    name: semaphore.service
    enabled: true
    daemon_reload: true

- name: Semaphore script
  ansible.builtin.template:
    src: semaphore.sh.j2
    dest: /usr/local/bin/semaphore.sh
    owner: "{{ user_name }}"
    group: root
    mode: "0700"

- name: Create Semaphore Nextcloud backup destination
  ansible.builtin.file:
    path: "{{ nextcloud_path }}/data/{{ nextcloud_homelab_user }}/files/{{ semaphore_backup_location | replace('Nextcloud:', '') }}"
    state: directory
    owner: "{{ nextcloud_uid }}"
    group: "{{ nextcloud_gid }}"
    mode: "0770"
  when: backup_local | default(false)

- name: Repair Semaphore Nextcloud backup destination ownership
  ansible.builtin.file:
    path: "{{ nextcloud_path }}/data/{{ nextcloud_homelab_user }}/files/{{ semaphore_backup_location | replace('Nextcloud:', '') }}"
    state: directory
    owner: "{{ nextcloud_uid }}"
    group: "{{ nextcloud_gid }}"
    recurse: true
  when: backup_local | default(false)

- name: Backup Semaphore DB Script
  ansible.builtin.template:
    src: backup_semaphore.sh.j2
    dest: /usr/local/bin/backup_semaphore.sh
    owner: root
    group: root
    mode: "0700"

- name: Backup Semaphore Daily
  ansible.builtin.cron:
    name: Backup Semaphore
    special_time: daily
    job: /usr/bin/bash /usr/local/bin/backup_semaphore.sh

- name: Start semaphore
  ansible.builtin.systemd:
    name: semaphore.service
    state: started
  when: not (apply_runtime_changes_on_reboot | default(false) | bool)
