---
- name: Create filesystem paths
  ansible.builtin.file:
    path: "{{ filesystem.initial_path | default(omit) }}"
    state: directory
  loop: "{{ file_systems }}"
  loop_control:
    loop_var: filesystem
  when:
    - ansible_facts['distribution'] == 'Archlinux'
    - filesystem.initial_path | default(omit) is defined

- name: Mount file systems
  ansible.builtin.shell:
    cmd: |
      mount "/dev/{{ lvm_name }}/{{ filesystem.name }}" {{ filesystem.initial_path | default(omit) }}
  loop: "{{ file_systems }}"
  loop_control:
    loop_var: filesystem
  when:
    - ansible_facts['distribution'] == 'Archlinux'
    - filesystem.initial_path | default(omit) is defined

- name: Create boot path
  ansible.builtin.file:
    path: "/mnt/boot"
    state: directory
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Mount Boot Filesystem
  ansible.builtin.shell:
    cmd: |
      mount "{{ disk }}p1" '/mnt/boot'
  when: ansible_facts['distribution'] == 'Archlinux'
