---
- name: Create paperless secret directory
  ansible.builtin.file:
    path: "{{ secret_env_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Paperless env file
  ansible.builtin.template:
    src: paperless.env.j2
    dest: "{{ secret_env_dir }}/paperless.env"
    owner: root
    group: root
    mode: "0600"

- name: Create paperless paths
  ansible.builtin.file:
    path: "{{ item_path }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0770"
  loop:
    - "{{ paperless_path }}"
    - "{{ paperless_data_path }}"
    - "{{ paperless_media_path }}"
    - "{{ paperless_export_path }}"
    - "{{ paperless_consume_path }}"

  loop_control:
    loop_var: item_path

- name: Paperless Service
  ansible.builtin.template:
    src: paperless_ngx.service.j2
    dest: /etc/systemd/system/paperless_ngx.service

- name: Enable paperless
  ansible.builtin.systemd:
    name: paperless_ngx.service
    enabled: true
    daemon_reload: true

- name: Paperless script
  ansible.builtin.template:
    src: paperless_ngx.sh.j2
    dest: /usr/local/bin/paperless_ngx.sh
    owner: "{{ user_name }}"
    group: root
    mode: "0700"

- name: Install zip and jq packages
  ansible.builtin.dnf:
    name:
      - zip
      - jq
    state: present

- name: Start paperless
  ansible.builtin.systemd:
    name: paperless_ngx.service
    state: started
  when: not (apply_runtime_changes_on_reboot | default(false) | bool)
