---
- name: Create main playbook path
  ansible.builtin.file:
    path: "{{ ansible_playbooks_path }}"
    state: directory
  when: ansible_facts['distribution'] == 'Debian'

- name: Ansible clone path
  ansible.builtin.file:
    path: "{{ git_data }}"
    state: directory
  when: ansible_facts['distribution'] == 'Debian'

- name: Clone Ansible Repo
  ansible.builtin.git:
    repo: https://github.com/MatthewDavidMiller/ansible_playbooks.git
    dest: "{{ git_data }}/ansible_playbooks"
  when: ansible_facts['distribution'] == 'Debian'

- name: Copy roles
  ansible.builtin.copy:
    src: "{{ git_data }}/ansible_playbooks/roles"
    dest: "{{ ansible_playbooks_path }}"
  when: ansible_facts['distribution'] == 'Debian'
