# Credits
# https://stackoverflow.com/questions/36059804/ansible-store-commands-stdout-in-new-variable
# https://github.com/SchemaStore/schemastore/issues/1397
# https://serverfault.com/questions/952498/ansible-multiline-results-and-loop
# https://serdima.wordpress.com/2018/04/23/tutorial-updating-dynamic-dns-with-ddclient/

---
- name: Create Wireguard container path
  ansible.builtin.file:
    path: "{{ vpn_path }}"
    state: directory
  when: ansible_facts['distribution'] == 'Debian'

- name: Create ddclient container path
  ansible.builtin.file:
    path: "{{ ddclient_path }}"
    state: directory
  when: ansible_facts['distribution'] == 'Debian'

- name: Create Wireguard container config path
  ansible.builtin.file:
    path: "{{ vpn_path }}/config"
    state: directory
  when: ansible_facts['distribution'] == 'Debian'

- name: Wireguard Module
  ansible.builtin.template:
    src: wireguard_module.j2
    dest: "/etc/modules-load.d/wireguard.conf"
  when: ansible_facts['distribution'] == 'Debian'

- name: Wireguard Service
  ansible.builtin.template:
    src: wireguard.service.j2
    dest: "/etc/systemd/system/wireguard.service"
  when: ansible_facts['distribution'] == 'Debian'

- name: Enable Wireguard
  ansible.builtin.systemd:
    name: wireguard.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian'

- name: Wireguard script
  ansible.builtin.template:
    src: wireguard.sh.j2
    dest: "/usr/local/bin/wireguard.sh"
  when: ansible_facts['distribution'] == 'Debian'

- name: Update VPN containers
  ansible.builtin.template:
    src: update_vpn_containers.sh.j2
    dest: "/usr/local/bin/update_vpn_containers.sh"
  when: ansible_facts['distribution'] == 'Debian'

- name: DDClient Service
  ansible.builtin.template:
    src: ddclient_container.service.j2
    dest: "/etc/systemd/system/ddclient_container.service"
  when: ansible_facts['distribution'] == 'Debian'

- name: Enable Ddclient
  ansible.builtin.systemd:
    name: ddclient_container.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian'

- name: DDClient script
  ansible.builtin.template:
    src: ddclient.sh.j2
    dest: "/usr/local/bin/ddclient.sh"
  when: ansible_facts['distribution'] == 'Debian'

- name: DDClient Config
  ansible.builtin.template:
    src: ddclient_config.j2
    dest: "{{ ddclient_path }}/ddclient.conf"
  when: ansible_facts['distribution'] == 'Debian'
