# Credits
# https://stackoverflow.com/questions/36059804/ansible-store-commands-stdout-in-new-variable
# https://github.com/SchemaStore/schemastore/issues/1397
# https://serverfault.com/questions/952498/ansible-multiline-results-and-loop
# https://serdima.wordpress.com/2018/04/23/tutorial-updating-dynamic-dns-with-ddclient/

---
- name: Install ddclient
  community.general.rpm_ostree_pkg:
    name: ddclient
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create Wireguard container path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/wireguard"
    state: directory
  when: ansible_facts['os_family'] == 'RedHat'

- name: Create Wireguard container config path
  ansible.builtin.file:
    path: "/home/{{ user_name }}/wireguard/config"
    state: directory
  when: ansible_facts['os_family'] == 'RedHat'

- name: Wireguard Service
  ansible.builtin.template:
    src: wireguard.service.j2
    dest: "/etc/systemd/system/wireguard.service"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Enable Wireguard
  ansible.builtin.systemd:
    name: wireguard.service
    enabled: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: DDClient Config
  ansible.builtin.template:
    src: ddclient_config.j2
    dest: "/etc/ddclient.conf"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Enable ddclient daemon
  ansible.builtin.lineinfile:
    path: /etc/default/ddclient
    regexp: "^run_daemon="
    line: run_daemon="true"
  when: ansible_facts['os_family'] == 'RedHat'
