---
- name: locale configuration
  ansible.builtin.template:
    src: locale.j2
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: set locale to generate
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: ^#?en_US\.UTF-8 UTF-8
    line: en_US.UTF-8 UTF-8
  when: ansible_facts['distribution'] == 'Archlinux'

- name: generate locale
  ansible.builtin.shell:
    cmd: |
      locale-gen
  become: "yes"
  when: ansible_facts['distribution'] == 'Archlinux'
