---
- name: Set default action for public to drop
  ansible.posix.firewalld:
    zone: public
    target: DROP
    permanent: yes
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Disable SSH in default zone
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: disabled
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Disable dhcpv6-client in default zone
  ansible.posix.firewalld:
    zone: public
    service: dhcpv6-client
    permanent: yes
    state: disabled
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Disable mdns in default zone
  ansible.posix.firewalld:
    zone: public
    service: mdns
    permanent: yes
    state: disabled
  when: ansible_facts['distribution'] == 'Archlinux'
