# Credits
# https://www.decodingdevops.com/ansible-when-file-exists/
# https://techviewleo.com/list-of-ansible-os-family-distributions-facts/

---
- name: Update System Script
  ansible.builtin.template:
    src: update_system.j2
    dest: "/usr/local/bin/update_system.sh"
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == 'Debian'

- name: Update System Script
  ansible.builtin.template:
    src: update_system_arch.j2
    dest: "/usr/local/bin/update_system.sh"
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == 'Archlinux'
