---
# Credits
# https://blog.fabiancdng.com/running-nextcloud-using-docker-and-traefik/
# https://medium.com/@containeroo/traefik-2-0-wildcard-lets-encrypt-certificates-1658370adc68
# https://kevinquillen.com/setting-traefik-2-local-ssl-certificate

- name: Create swag container path
  ansible.builtin.file:
    path: "{{ swag_path }}"
    state: directory
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian'

- name: Swag Service
  ansible.builtin.template:
    src: swag_container.service.j2
    dest: "/etc/systemd/system/swag_container.service"
  when: ansible_facts['distribution'] == 'Debian'

- name: Enable Swag
  ansible.builtin.systemd:
    name: swag_container.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian'

- name: Swag script
  ansible.builtin.template:
    src: swag_container.sh.j2
    dest: "/usr/local/bin/swag_container.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian'
