---
# Credits
# https://blog.fabiancdng.com/running-nextcloud-using-docker-and-traefik/
# https://medium.com/@containeroo/traefik-2-0-wildcard-lets-encrypt-certificates-1658370adc68
# https://kevinquillen.com/setting-traefik-2-local-ssl-certificate

- name: Create swag container path
  ansible.builtin.file:
    path: "{{ swag_path }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0770"
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create swag dns-config path
  ansible.builtin.file:
    path: "{{ swag_path }}/dns-conf"
    state: directory
    owner: 1000
    group: 1000
    mode: "0770"
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create swag proxy-confs path
  ansible.builtin.file:
    path: "{{ swag_path }}/nginx/proxy-confs"
    state: directory
    owner: 1000
    group: 1000
    mode: "0770"
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Create swag site-confs path
  ansible.builtin.file:
    path: "{{ swag_path }}/nginx/site-confs"
    state: directory
    owner: 1000
    group: 1000
    mode: "0770"
    recurse: true
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag Service
  ansible.builtin.template:
    src: swag_container.service.j2
    dest: "/etc/systemd/system/swag_container.service"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Enable Swag
  ansible.builtin.systemd:
    name: swag_container.service
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag script
  ansible.builtin.template:
    src: swag_container.sh.j2
    dest: "/usr/local/bin/swag_container.sh"
    owner: 1000
    group: 1000
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag porkbun DNS config
  ansible.builtin.template:
    src: porkbun.ini.j2
    dest: "{{ swag_path }}/dns-conf/porkbun.ini"
    owner: 1000
    group: 1000
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag proxy config
  ansible.builtin.template:
    src: "{{ config_name.name }}_proxy.conf.j2"
    dest: "{{ swag_path }}/nginx/proxy-confs/{{ config_name.name }}.subdomain.conf"
    owner: 1000
    group: 1000
    mode: "0770"
  loop: "{{ proxy_config }}"
  loop_control:
    loop_var: config_name
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag ssl config
  ansible.builtin.template:
    src: "ssl.conf.j2"
    dest: "{{ swag_path }}/nginx/ssl.conf"
    owner: 1000
    group: 1000
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag default config
  ansible.builtin.template:
    src: "default.conf.j2"
    dest: "{{ swag_path }}/nginx/site-confs/default.conf"
    owner: 1000
    group: 1000
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'

- name: Swag proxy config
  ansible.builtin.template:
    src: "proxy.conf.j2"
    dest: "{{ swag_path }}/nginx/proxy.conf"
    owner: 1000
    group: 1000
    mode: "0770"
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Archlinux'
