---
- name: Create traefik container path
  ansible.builtin.file:
    path: "{{ traefik_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create traefik config path
  ansible.builtin.file:
    path: "{{ traefik_path }}/config"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Initialize acme.json
  ansible.builtin.copy:
    content: ""
    dest: "{{ traefik_path }}/acme.json"
    owner: root
    group: root
    mode: "0600"
    force: false

- name: Traefik static config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ traefik_path }}/traefik.yml"
    owner: root
    group: root
    mode: "0640"

- name: Traefik TLS options
  ansible.builtin.template:
    src: tls.yml.j2
    dest: "{{ traefik_path }}/config/tls.yml"
    owner: root
    group: root
    mode: "0640"

- name: Traefik security middlewares
  ansible.builtin.template:
    src: security.yml.j2
    dest: "{{ traefik_path }}/config/security.yml"
    owner: root
    group: root
    mode: "0640"

- name: Traefik dashboard router
  ansible.builtin.template:
    src: dashboard.yml.j2
    dest: "{{ traefik_path }}/config/dashboard.yml"
    owner: root
    group: root
    mode: "0640"

- name: Traefik service proxy configs
  ansible.builtin.template:
    src: service_proxy.yml.j2
    dest: "{{ traefik_path }}/config/{{ config_name.name }}.yml"
    owner: root
    group: root
    mode: "0640"
  loop: "{{ proxy_config }}"
  loop_control:
    loop_var: config_name

- name: Traefik service unit
  ansible.builtin.template:
    src: traefik_container.service.j2
    dest: "/etc/systemd/system/traefik_container.service"

- name: Enable Traefik
  ansible.builtin.systemd:
    name: traefik_container.service
    enabled: yes
    daemon_reload: yes

- name: Traefik launch script
  ansible.builtin.template:
    src: traefik_container.sh.j2
    dest: "/usr/local/bin/traefik_container.sh"
    owner: root
    group: root
    mode: "0750"
