---
- name: Create sway or i3 config path
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/{{ wm }}
    owner: "{{ user_name }}"
    state: directory
  when:
    - ansible_facts['distribution'] == 'Archlinux'

- name: Sway or i3 configuration
  ansible.builtin.template:
    src: sway.j2
    dest: /home/{{ user_name }}/.config/{{ wm }}/config
    owner: "{{ user_name }}"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Sway or i3 autostart script
  ansible.builtin.template:
    src: sway_autostart.j2
    dest: /usr/local/bin/{{ wm }}_autostart.sh
    owner: "{{ user_name }}"
    mode: "0744"
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Autostart sway or i3 at login
  ansible.builtin.blockinfile:
    path: "/home/{{ user_name }}/.bashrc"
    block: |
      # If running from tty1 start sway
      if [ "$(tty)" = "/dev/tty1" ]; then
        {{ autostart_wm }}
      fi
    marker: "{mark}"
    owner: "{{ user_name }}"
    marker_begin: "# Autostart {{ wm }}"
    marker_end: "# Autostart {{ wm }}=================================================================================================================="
  when:
    - ansible_facts['distribution'] == 'Archlinux'

- name: Fix Java Applications in Sway
  ansible.builtin.blockinfile:
    path: "/home/{{ user_name }}/.bashrc"
    owner: "{{ user_name }}"
    block: "export _JAVA_AWT_WM_NONREPARENTING=1"
    marker: "{mark}"
    marker_begin: "# Fix Java Applications in Sway"
    marker_end: " Fix Java Applications in Sway=================================================================================================================="
  when:
    - ansible_facts['distribution'] == 'Archlinux'
