---
- name: Create Logical Volume group
  community.general.lvg:
    vg: "{{ lvm_name }}"
    pvs: "/dev/mapper/mycrypt"
    pvresize: true
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Create logical volumes
  community.general.lvol:
    vg: "{{ lvm_name }}"
    lv: "{{ volume.name }}"
    size: "{{ volume.partition_size }}"
  loop: "{{ logical_volumes }}"
  loop_control:
    loop_var: volume
  when:
    - ansible_facts['distribution'] == 'Archlinux'
