---
- name: Set sftp ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Subsystem\\s*sftp"
    line: Subsystem sftp /usr/lib/openssh/sftp-server

- name: Set ssh authorized keys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AuthorizedKeysFile"
    line: "AuthorizedKeysFile .ssh/authorized_keys"

- name: Set Challenge Response Auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"

- name: Set password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Set empty password
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"

- name: Set GSSAP Auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"

- name: Set root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"

- name: Set max auth tries
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^MaxAuthTries"
    line: "MaxAuthTries 6"

- name: Set pubkey auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"

- name: Set PAM
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^UsePAM"
    line: "UsePAM no"
