---
- name: Generate SSH Key Pair
  hosts: ansible

  tasks:
    - name: Generate an OpenSSH keypair
      ansible.builtin.command:
        argv:
          - ssh-keygen
          - -q
          - -t
          - ed25519
          - -N
          - ""
          - -f
          - "/home/{{ user_name }}/{{ key_name }}"
      args:
        creates: "/home/{{ user_name }}/{{ key_name }}"
