---
- name: Apply host package updates on vm2
  hosts: vm2
  vars:
    standard_update_enable_epel: true
    standard_update_apply_security_updates: false
    standard_update_apply_full_updates: true
  roles:
    - standard_update_packages
