---
- name: Hostname file configuration
  ansible.builtin.template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['distribution'] == 'Archlinux'
